export type SessionKind = "fx" | "index" | "metal" | "crypto" | "energy";
export type MarketCategory = "forex" | "index" | "metal" | "energy" | "crypto";

export type Instrument = {
  id: string;
  label: string;
  yahoo: string;
  digits: number;
  pip: number;
  spread: number;
  session: SessionKind;
  group: string;
  category: MarketCategory;
  description: string;
};

export const CATEGORIES: Array<{ id: MarketCategory; label: string }> = [
  { id: "forex", label: "Forex" },
  { id: "index", label: "Indici" },
  { id: "metal", label: "Metalli" },
  { id: "energy", label: "Energia" },
  { id: "crypto", label: "Crypto" },
];

export const INSTRUMENTS: Instrument[] = [
  {
    id: "EURUSD",
    label: "EUR/USD",
    yahoo: "EURUSD=X",
    digits: 5,
    pip: 0.0001,
    spread: 0.00008,
    session: "fx",
    group: "fx-eu",
    category: "forex",
    description: "Coppia maggiore. Londra e New York.",
  },
  {
    id: "GBPUSD",
    label: "GBP/USD",
    yahoo: "GBPUSD=X",
    digits: 5,
    pip: 0.0001,
    spread: 0.00012,
    session: "fx",
    group: "fx-eu",
    category: "forex",
    description: "Correlata all'euro. Non raddoppiare.",
  },
  {
    id: "USDJPY",
    label: "USD/JPY",
    yahoo: "JPY=X",
    digits: 3,
    pip: 0.01,
    spread: 0.012,
    session: "fx",
    group: "fx-usd",
    category: "forex",
    description: "Yen. Sensibile a Tokyo e alla Fed.",
  },
  {
    id: "USDCHF",
    label: "USD/CHF",
    yahoo: "CHF=X",
    digits: 5,
    pip: 0.0001,
    spread: 0.00012,
    session: "fx",
    group: "fx-usd",
    category: "forex",
    description: "Franco. Spesso specchio dell'EUR/USD.",
  },
  {
    id: "AUDUSD",
    label: "AUD/USD",
    yahoo: "AUDUSD=X",
    digits: 5,
    pip: 0.0001,
    spread: 0.00012,
    session: "fx",
    group: "fx-au",
    category: "forex",
    description: "Dollaro australiano. Asia e materie.",
  },
  {
    id: "USDCAD",
    label: "USD/CAD",
    yahoo: "CAD=X",
    digits: 5,
    pip: 0.0001,
    spread: 0.00013,
    session: "fx",
    group: "fx-usd",
    category: "forex",
    description: "Loonie. Legato al petrolio.",
  },
  {
    id: "NZDUSD",
    label: "NZD/USD",
    yahoo: "NZDUSD=X",
    digits: 5,
    pip: 0.0001,
    spread: 0.00016,
    session: "fx",
    group: "fx-au",
    category: "forex",
    description: "Kiwi. Meno liquido: stop più larghi.",
  },
  {
    id: "EURGBP",
    label: "EUR/GBP",
    yahoo: "EURGBP=X",
    digits: 5,
    pip: 0.0001,
    spread: 0.0001,
    session: "fx",
    group: "fx-eu",
    category: "forex",
    description: "Cross europeo. Stesso rischio di EUR e GBP.",
  },
  {
    id: "EURJPY",
    label: "EUR/JPY",
    yahoo: "EURJPY=X",
    digits: 3,
    pip: 0.01,
    spread: 0.018,
    session: "fx",
    group: "fx-eu",
    category: "forex",
    description: "Cross volatile. Non accoppiarlo a EUR/USD.",
  },
  {
    id: "GBPJPY",
    label: "GBP/JPY",
    yahoo: "GBPJPY=X",
    digits: 3,
    pip: 0.01,
    spread: 0.025,
    session: "fx",
    group: "fx-eu",
    category: "forex",
    description: "Il più nervoso dei cross. Size piccola.",
  },
  {
    id: "EURCHF",
    label: "EUR/CHF",
    yahoo: "EURCHF=X",
    digits: 5,
    pip: 0.0001,
    spread: 0.00014,
    session: "fx",
    group: "fx-eu",
    category: "forex",
    description: "Range stretti. ATR piccolo: attenzione allo spread.",
  },
  {
    id: "AUDJPY",
    label: "AUD/JPY",
    yahoo: "AUDJPY=X",
    digits: 3,
    pip: 0.01,
    spread: 0.02,
    session: "fx",
    group: "fx-au",
    category: "forex",
    description: "Risk-on / risk-off. Sessione Asia.",
  },
  {
    id: "XAUUSD",
    label: "Oro",
    yahoo: "GC=F",
    digits: 2,
    pip: 0.1,
    spread: 0.25,
    session: "metal",
    group: "metal",
    category: "metal",
    description: "Stop sull'ATR, non a sentimento.",
  },
  {
    id: "XAGUSD",
    label: "Argento",
    yahoo: "SI=F",
    digits: 3,
    pip: 0.01,
    spread: 0.02,
    session: "metal",
    group: "metal",
    category: "metal",
    description: "Più nervoso dell'oro. Una sola posizione metallo.",
  },
  {
    id: "US500",
    label: "S&P 500",
    yahoo: "^GSPC",
    digits: 2,
    pip: 0.25,
    spread: 0.4,
    session: "index",
    group: "us-index",
    category: "index",
    description: "Sessione cash USA.",
  },
  {
    id: "US100",
    label: "Nasdaq 100",
    yahoo: "^NDX",
    digits: 2,
    pip: 0.5,
    spread: 0.8,
    session: "index",
    group: "us-index",
    category: "index",
    description: "Correlato all'S&P. Un indice USA alla volta.",
  },
  {
    id: "US30",
    label: "Dow Jones",
    yahoo: "^DJI",
    digits: 1,
    pip: 1,
    spread: 2,
    session: "index",
    group: "us-index",
    category: "index",
    description: "Stesso rischio degli altri indici USA.",
  },
  {
    id: "GER40",
    label: "DAX",
    yahoo: "^GDAXI",
    digits: 1,
    pip: 1,
    spread: 1.2,
    session: "index",
    group: "eu-index",
    category: "index",
    description: "Francoforte. Sessione europea.",
  },
  {
    id: "UK100",
    label: "FTSE 100",
    yahoo: "^FTSE",
    digits: 1,
    pip: 1,
    spread: 1,
    session: "index",
    group: "eu-index",
    category: "index",
    description: "Londra. Correlato al DAX.",
  },
  {
    id: "FRA40",
    label: "CAC 40",
    yahoo: "^FCHI",
    digits: 1,
    pip: 1,
    spread: 1,
    session: "index",
    group: "eu-index",
    category: "index",
    description: "Parigi. Stesso gruppo europeo.",
  },
  {
    id: "ESP35",
    label: "IBEX 35",
    yahoo: "^IBEX",
    digits: 1,
    pip: 1,
    spread: 1.5,
    session: "index",
    group: "eu-index",
    category: "index",
    description: "Madrid.",
  },
  {
    id: "JPN225",
    label: "Nikkei 225",
    yahoo: "^N225",
    digits: 1,
    pip: 5,
    spread: 8,
    session: "index",
    group: "asia-index",
    category: "index",
    description: "Tokyo. Meglio in sessione Asia.",
  },
  {
    id: "AUS200",
    label: "ASX 200",
    yahoo: "^AXJO",
    digits: 1,
    pip: 1,
    spread: 2,
    session: "index",
    group: "asia-index",
    category: "index",
    description: "Sydney.",
  },
  {
    id: "USOIL",
    label: "Petrolio WTI",
    yahoo: "CL=F",
    digits: 2,
    pip: 0.01,
    spread: 0.03,
    session: "energy",
    group: "energy",
    category: "energy",
    description: "Inventari e OPEC. Un solo energy.",
  },
  {
    id: "UKOIL",
    label: "Petrolio Brent",
    yahoo: "BZ=F",
    digits: 2,
    pip: 0.01,
    spread: 0.03,
    session: "energy",
    group: "energy",
    category: "energy",
    description: "Correlato al WTI. Non entrambi.",
  },
  {
    id: "NATGAS",
    label: "Gas naturale",
    yahoo: "NG=F",
    digits: 3,
    pip: 0.001,
    spread: 0.006,
    session: "energy",
    group: "energy",
    category: "energy",
    description: "Spike violenti. Size minima.",
  },
  {
    id: "BTCUSD",
    label: "Bitcoin",
    yahoo: "BTC-USD",
    digits: 1,
    pip: 1,
    spread: 12,
    session: "crypto",
    group: "crypto",
    category: "crypto",
    description: "24/7. Time stop obbligatorio.",
  },
  {
    id: "ETHUSD",
    label: "Ethereum",
    yahoo: "ETH-USD",
    digits: 2,
    pip: 0.1,
    spread: 1.2,
    session: "crypto",
    group: "crypto",
    category: "crypto",
    description: "Correlato al Bitcoin. Una crypto alla volta.",
  },
  {
    id: "SOLUSD",
    label: "Solana",
    yahoo: "SOL-USD",
    digits: 2,
    pip: 0.01,
    spread: 0.08,
    session: "crypto",
    group: "crypto",
    category: "crypto",
    description: "Più nervosa di ETH. Weekend ok.",
  },
];

export const TIMEFRAMES = [
  { id: "5m", label: "5 min", yahoo: "5m", range: "5d", minutes: 5, higher: "1h" },
  { id: "15m", label: "15 min", yahoo: "15m", range: "1mo", minutes: 15, higher: "1h" },
  { id: "1h", label: "1 ora", yahoo: "60m", range: "3mo", minutes: 60, higher: "1d" },
  { id: "4h", label: "4 ore", yahoo: "60m", range: "6mo", minutes: 240, higher: "1d" },
] as const;

export type TimeframeId = (typeof TIMEFRAMES)[number]["id"];

export function getInstrument(id: string): Instrument {
  return INSTRUMENTS.find((item) => item.id === id) ?? INSTRUMENTS[0];
}

export function instrumentsByCategory(category: MarketCategory): Instrument[] {
  return INSTRUMENTS.filter((item) => item.category === category);
}

export function formatPrice(value: number, digits: number): string {
  return value.toLocaleString("it-IT", {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  });
}

export function formatMoney(value: number, currency = "EUR"): string {
  return value.toLocaleString("it-IT", {
    style: "currency",
    currency,
    maximumFractionDigits: 2,
  });
}
